### ISSUE TITLE
NPE check

### ISSUE THREAD

**Issue by mstaskiewicz** [scina/familyapp#7]
https://github.com/scina/familyapp/blob/59cfd155ce32ab1d14d903c428208de8ed08d2e4/src/main/java/pl/dudekjunior/familyapp/models/servicies/FatherService.java#L28

**Comment by scina** [comment]
Obsługa wyjątków jest podobno ciężka dla maszyny, więc zrobię Optionalem - trzeba będzie zrobić jakiś warunek przy returnie lub przy próbie jego użycia gdzieś dalej.

**Comment by mstaskiewicz** [comment]
Kto Ci naopowiadał o problemie z wyjątkami? W początkach Javy obawiano się
takich rzeczy. Teraz nikt nie zwraca uwagi na to. To nie jest jakiś
wyśrubowany system, a wyjątki to dobry wzorzec.

śr., 21 lis 2018 o 21:49 Przemysław Dudek <notifications@github.com>
napisał(a):

**Comment by scina** [comment]
Ok, to przy wyjątku, rzucić go dalej, czy już w serwisie go jakoś obsłużyć?

**Comment by mstaskiewicz** [comment]
Rzucaj dalej. Stwórz jakiś swój exception chyba, że ostatnio w Springu pojawiły się jakieś specjalne do tego. Controller dopiero powinien to obsłużyć i wyrzucić np. 404
